---
include:
  - board: ergohaven
    shield: velvet_v3_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: velvet_v3_left
    keymap: velvet_v3_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_right
  - board: ergohaven
    shield: velvet_v3_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_qube-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_qube qube dongle_screen
    keymap: velvet_v3_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_qube_ruen-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_left_qube

  - board: ergohaven
    shield: velvet_v3_ui_left
  - board: ergohaven
    shield: velvet_v3_ui_right
    keymap: velvet_v3_ui_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_right_ruen-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_ui_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: velvet_v3_ui_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_qube-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_ui_qube qube dongle_screen
    keymap: velvet_v3_ui_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_qube_ruen-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_ui_right_qube

  - board: ergohaven
    shield: trackball
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: ergohaven
    shield: settings_reset
